-- Generated Seed Data
BEGIN TRANSACTION;
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'عيد التحرير', '2025-12-08', '10:00 AM', 180, 'عطلة كاملة', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'عبير الطبل', '2025-12-09', '04:00 PM', 150, 'طالبة لحالها', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (3, 'إدارة مشاريع مجتلات البناء', '2025-12-09', '10:00 AM', 180, 'Filament course', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'حسين', '2025-12-16', '02:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'زينب حمشو', '2025-12-09', '02:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'عبير الطبل', '2025-12-10', '05:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'فراغ', '2025-12-09', '10:00 AM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'عيد التحرير', '2025-12-08', '10:00 AM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'عيد التحرير', '2025-12-08', '10:00 AM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'زينب حمشو', '2025-12-16', '12:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'متجر مجوهرات', '2025-12-16', '03:30 PM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'نشوى وجنى', '2025-12-10', '02:30 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'سوزان', '2025-12-10', '11:00 AM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (3, 'إدارة مشاريع مجالات البناء', '2025-12-11', '09:00 AM', 180, 'Laravel livewire + كتاب المشروع', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'القارئ الذكي', '2025-12-10', '09:00 AM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'روبوت دردشة طلاب معهد', '2025-12-11', '10:30 AM', 90, '6 طلاب', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'تشويش', '2025-12-11', '12:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'معهد', '2025-12-11', '01:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'يافعين', '2025-12-11', '03:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'اسيمة', '2025-12-11', '04:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'مشروع روبوت تعليم الاطفال وطنية', '2025-12-15', '01:30 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'روبوت دردشة طلاب معهد', '2025-12-13', '11:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'روبوت اطفاء الحريق', '2025-12-14', '03:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'معهد حاسوب', '2025-12-13', '10:00 AM', 120, '8 طلاب', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'كشف الاصابات في النادي', '2025-12-14', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'كشف الاصابات في النادي', '2025-12-17', '01:30 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'القارئ الذكي', '2025-12-16', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'تشويش', '2025-12-14', '12:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'كشف الاصابات في النادي', '2025-12-13', '12:00 PM', 90, 'جلسة الكتاب', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (3, 'إدارة مشاريع مجالات البناء', '2025-12-16', '09:00 AM', 120, 'استفسارات', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'مخلصة الريس', '2025-12-15', '03:00 PM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'راما حلو', '2025-12-14', '02:30 PM', 150, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'جنى ونشوى - توثيق الاضرار الذكي', '2025-12-18', '01:00 PM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'تشويش', '2025-12-16', '12:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'معهد حاسوب', '2025-12-16', '01:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'ايمن حنبظلي', '2025-12-17', '03:30 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'الاء الصباح', '2025-12-16', '10:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'صندوق الدواء الخيري', '2025-12-18', '10:30 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'تعليم الاطفال افتراضية', '2025-12-18', '01:00 PM', 120, 'من 1', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'خالد الحسين', '2025-12-18', '12:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'زاكي ابو جدعان', '2025-12-22', '02:30 PM', 60, 'امن سيبراني مع ندى', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'تشويش', '2025-12-22', '01:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'معهد', '2025-12-24', '01:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'اسيمة', '2025-12-24', '03:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'آية', '2025-12-23', '12:00 PM', 120, 'نحتاج غرفة الشاشة', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'حسين', '2025-12-20', '10:00 AM', 120, 'كتاب فقط', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'متجر مجوهرات', '2025-12-22', '03:30 PM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'عبير الطبل', '2025-12-17', '05:00 PM', 150, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'معهد VPN', '2025-12-17', '12:30 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'اجتماع تنظيم الاسرة خارج المكتب', '2025-12-22', '11:00 AM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'عبير الطبل', '2025-12-18', '04:00 PM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'سوزان', '2025-12-18', '10:30 AM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'روبوت اطفاء الحريق', '2025-12-20', '02:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'مخلصة الريس', '2025-12-24', '03:00 PM', 150, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'احمد', '2025-12-20', '04:00 PM', 150, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'الاء الصباح', '2025-12-23', '10:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'صندوق الدواء الخيري', '2025-12-24', '08:30 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'تحكم باللابتوب عن بعد', '2025-12-20', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'تحكم باللابتوب عن بعد', '2025-12-25', '11:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'عبير الطبل', '2025-12-23', '02:30 PM', 180, 'موعد لآخر اليوم', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'ثريا القلعة', '2025-12-25', '02:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'كشف الاصابات في النادي', '2025-12-23', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'تشويش', '2025-12-23', '11:30 AM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'حمص', '2025-12-28', '10:00 AM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (3, 'إدارة مشاريع مجالات البناء finally', '2025-12-25', '09:30 AM', 90, 'جلسة التدريب ع العرض التقديمي', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'الربط الشبكي معهد', '2025-12-23', '12:30 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'تشويش', '2025-12-25', '01:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'سوزان', '2025-12-25', '10:30 AM', 150, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'زينب حمشو وسدرة وجنات', '2025-12-23', '02:00 PM', 150, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'القارئ الذكي', '2025-12-25', '02:00 PM', 120, 'جلسة الكتاب', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'القارئ الذكي', '2025-12-23', '01:00 PM', 120, 'جلسة كتاب', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'كشف الاصابات في النادي', '2025-12-24', '01:00 PM', 120, 'ه', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'اية - امنة - هبة - منصة بايثون', '2025-12-29', '12:30 PM', 180, 'نحتاج شاشة', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'عبير الطبل', '2025-12-24', '02:00 PM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'لوح افتراضي', '2025-12-24', '10:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'تحكم باللابتوب عن بعد', '2025-12-25', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'تعليم الاطفال افتراضية', '2025-12-24', '10:30 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'اسيمة', '2025-12-25', '03:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'عبير الطبل', '2025-12-25', '03:30 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'مخلصة الريس', '2025-12-25', '04:00 PM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'سوزان', '2025-12-29', '10:30 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'موعد الاستاذ عبد الغني مع ندى', '2025-12-29', '03:30 PM', 120, 'لا تنسى ولا تحط اي موعد استاااااااااااذ', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'طلاب معهد 7 طلاب مجموعة دجانة', '2025-12-30', '11:00 AM', 180, 'قاعة الشاشة حصرا وشكرا', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'قلادة ذكية', '2025-12-30', '10:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'صندوق الدواء الخيري', '2025-12-28', '09:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'تصميم وتنفيذ طرف صناعي لذوي الاحتياجات الخاصة', '2025-12-27', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'جنى ونشوى - توثيق الاضرار الذكي', '2025-12-28', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'كشف الاصابات في النادي', '2026-01-01', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'القارئ الذكي', '2025-12-27', '02:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'تشويش', '2026-01-01', '01:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'اسيمة', '2026-01-01', '03:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'طلاب الربط الشبكي', '2025-12-30', '10:00 AM', 60, 'القاعة الكبيرة', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'طلاب الربط الشبكي 7', '2025-12-30', '11:00 AM', 120, 'القاعة الخارجية كاملة 7 طلااااااب', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'هادي', '2025-12-29', '04:00 PM', 30, 'ع الاغلب خارج المكتب', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'عبير الطبل', '2025-12-28', '04:00 PM', 150, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'جنى ونشوى - توثيق الاضرار الذكي', '2025-12-30', '02:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'تحكم باللابتوب عن بعد', '2025-12-28', '11:30 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'صندوق الدواء الخيري', '2025-12-29', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'سوزان', '2026-01-06', '10:30 AM', 150, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'اية - امنة - هبة - منصة بايثون', '2025-12-31', '12:00 PM', 180, '7 طلاب حجز قاعتين', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'تنفيذ الربط الشبكي VPN', '2026-01-03', '10:30 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'طلاب تطبيقية 8 طلاب', '2026-01-01', '12:00 PM', 180, '8 طلاب بنفس القاعة عند الشاشة', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'تشويش', '2026-01-06', '02:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'اسيمة', '2026-01-06', '03:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'فاطمة الدباغ', '2026-01-08', '02:30 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'روبوت دردشة طلاب معهد', '2026-01-05', '09:00 AM', 120, 'عدد الطلاب ٨ بالقاعة تبع الشاشة', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'روبوت دردشة طلاب معهد', '2026-01-08', '09:00 AM', 120, 'عدد الطلاب ٨ بالقاعة تبع الشاشة', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'طلاب درون بعد حمص', '2026-01-04', '03:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (3, 'بحوث', '2025-12-28', '05:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'طلاب معهد', '2026-01-05', '06:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (3, 'بحوث', '2025-12-28', '05:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (3, 'بحوث', '2025-12-28', '05:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (3, 'بحوث', '2026-01-04', '05:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'اسيمة', '2026-01-10', '03:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'طلاب معهد', '2026-01-07', '07:00 PM', 150, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'كشف الاصابات في النادي', '2026-01-07', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'مريانا', '2026-01-08', '11:00 AM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (6, 'Hadi', '2026-01-06', '07:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'هادي', '2025-12-29', '04:00 PM', 30, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (3, 'بحوث', '2026-01-08', '05:30 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'طلاب درون', '2026-01-08', '04:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'فاطمة الدباغ', '2026-01-12', '01:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'سوزان', '2026-01-12', '11:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'تعليم الاطفال افتراضية', '2026-01-11', '01:30 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'تشويش', '2026-01-10', '02:00 PM', 60, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'معهد VPN', '2026-01-15', '11:00 AM', 90, 'بدنا القاعدة يلي جوا', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'طلاب معهد', '2026-01-12', '03:00 PM', 150, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (4, 'كشف الاصابات في النادي', '2026-01-10', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'اسيمة', '2026-01-12', '03:00 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'صندوق الدواء الخيري', '2026-01-12', '09:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'صندوق الدواء الخيري', '2026-01-14', '09:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'روبوت دردشة طلاب معهد', '2026-01-15', '09:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'تحكم باللابتوب عن بعد', '2026-01-14', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'اسيمة', '2026-01-14', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'طلاب معهد بشرى بدرة', '2026-01-14', '03:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'روبوت دردشة طلاب معهد', '2026-01-13', '09:00 AM', 120, 'عدد ٨ طلاب', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'لوح افتراضي', '2026-01-13', '11:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'الاء الصباح', '2026-01-15', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'حسين ذراع', '2026-01-17', '12:30 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'نظام سرقة محلات الدهب', '2026-01-14', '03:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'لوح افتراضي', '2026-01-15', '11:00 AM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'زينب حمشو وسدرة وجنات', '2026-01-15', '01:00 PM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'جنى ونشوى - توثيق الاضرار الذكي', '2026-01-15', '02:00 PM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'اية - امنة - هبة - منصة بايثون', '2026-01-19', '11:00 AM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'مايكل', '2026-01-17', '03:00 PM', 150, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (1, 'تشويش', '2026-01-22', '03:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'نظام سرقة محلات الدهب', '2026-01-21', '03:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'كشف الاصابات في النادي', '2026-01-21', '01:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'نظام سرقة محلات الدهب', '2026-01-19', '03:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'مشروع روبوت تعليم الاطفال وطنية', '2026-01-20', '10:00 AM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'زينب حمشو وسدرة وجنات', '2026-01-19', '12:00 PM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'نشوى وجنى', '2026-01-19', '12:00 PM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'طلاب معهد 7 طلاب مجموعة دجانة', '2026-01-21', '10:00 AM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'تحليل سلوك الطلاب', '2026-01-20', '02:00 PM', 120, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'سعاد المصري', '2026-01-19', '01:30 PM', 90, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (2, 'روبوت دردشة طلاب معهد', '2026-01-22', '10:00 AM', 120, 'عدد ٨', 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'اية - امنة - هبة - منصة بايثون', '2026-01-22', '11:30 AM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'زينب حمشو وسدرة وجنات', '2026-01-22', '12:00 PM', 180, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'حسين ذراع', '2026-01-21', '02:00 PM', 150, NULL, 'none');
INSERT INTO appointments (user_id, title, appointment_date, start_time, duration_minutes, notes, recurrence_type) VALUES (5, 'طلاب معهد', '2026-01-20', '07:30 PM', 150, NULL, 'none');
INSERT INTO general_notes (user_id, title, content, color_code) VALUES (5, 'عبد الهادي نسيان يستلم اخر دفعة', 'ضلت دفعتك الاخيرة بالصندوق وعليها اسمك', '#E91E63');
COMMIT;
